### ISSUE TITLE
More exchanges

### ISSUE THREAD

**Issue by gsoros** [gsoros/GTrader#4]
- OKC Spot
- OKC CNY
- Finex?
- Huobi
- 1Broke
- ...

**Comment by vitoo** [comment]
Bittrex  (high fees, but lots of alts)
Binance (low fees :+1:  )

**Comment by gsoros** [comment]
> Check out this to handle every exchange with one php lib : https://github.com/ccxt/ccxt

Thanks for the tip, we are using CCXT now.
