### ISSUE TITLE
It worked fine until i registered, then this error came. :(

### ISSUE THREAD

**Issue by d3vilsn0w** [gsoros/GTrader#8]
https://i.gyazo.com/6f005c70fe3fd80dc2f84394ef4e5919.png

**Comment by gsoros** [comment]
What version of PHP are you using?

**Comment by d3vilsn0w** [comment]
PHP 7.1.0, Which one should i try with?

**Comment by gsoros** [comment]
I'm still on 7.0.x
Changed some default params from empty strings to nulls, can you give it a try?

**Comment by d3vilsn0w** [comment]
There you go.
https://i.gyazo.com/cc071b762255370be7a0581a2a9cf984.png

**Comment by gsoros** [comment]
Looks like I'll need to install 7.1 and update many default params, it might take a few days ...

**Comment by d3vilsn0w** [comment]
i'll wait, Thank you. Great work!

**Comment by gsoros** [comment]
I cannot reproduce this on PHP 7.1.5.
I think the error is coming from "function foo(bool $param = false)".
Type hinting scalars was introduced in 7.0, are you sure you are not running 5.x?

**Comment by gsoros** [comment]
You can check the version by appending /phpinfo to the URL when APP_ENV=local in .env.

**Comment by d3vilsn0w** [comment]
https://i.gyazo.com/e71eb4e0725a19fa402265c068afb2a6.png :/

**Comment by d3vilsn0w** [comment]
I tried it on 7.0.x this morning and this comes up
https://i.gyazo.com/6329940c17f2026ddb62e1d8ee370260.png

**Comment by gsoros** [comment]
Have you run "npm run dev"?

**Comment by d3vilsn0w** [comment]
I completely forgot about it, thanks for reminding me, seems like things are working out on this PHP build. 
Now it says "FANN extension not loaded". I'll look into that, Thanks for the help! 👍

**Comment by gsoros** [comment]
Well, I have to admit that installing this software is not a piece of cake at this alpha stage. In the future I'll look into creating a docker image.

The instructions for the fann extension are at http://php.net/manual/en/fann.installation.php

Good luck!
